[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32dev
lib_extra_dirs = ../../..
build_unflags =
    -std=gnu++11
    -std=gnu++14
    -std=gnu++17
build_flags = -std=gnu++20

lib_deps =
    EDP-System=https://github.com/ESPressio-Development-Platform/EDP-System.git#main
    EDP-BoundedTypes=https://github.com/ESPressio-Development-Platform/EDP-BoundedTypes.git#main
    EDP-Localisation=https://github.com/ESPressio-Development-Platform/EDP-Localisation.git#main
framework = arduino
